name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  NODE_VERSION: '20.x'

jobs:
  e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: privatesocial
          MYSQL_USER: privatesocial_user
          MYSQL_PASSWORD: privatesocial_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: PrivateSocial.Web.React/package-lock.json

    - name: Install .NET dependencies
      run: dotnet restore

    - name: Build .NET solution
      run: dotnet build --no-restore

    - name: Install Node dependencies
      working-directory: ./PrivateSocial.Web.React
      run: npm ci

    - name: Install Playwright browsers
      working-directory: ./PrivateSocial.Web.React
      run: npx playwright install --with-deps

    - name: Update database connection string
      run: |
        echo "Updating connection string for CI environment"
        sed -i 's/"privatesocial": ".*"/"privatesocial": "Server=localhost;Port=3306;Database=privatesocial;User=privatesocial_user;Password=privatesocial_password;"/' PrivateSocial.ApiService/appsettings.json

    - name: Run database migrations
      run: |
        dotnet tool install --global dotnet-ef
        dotnet ef database update --project PrivateSocial.ApiService || echo "No migrations to apply"
      env:
        ConnectionStrings__privatesocial: "Server=localhost;Port=3306;Database=privatesocial;User=privatesocial_user;Password=privatesocial_password;"

    - name: Start API Service
      run: |
        cd PrivateSocial.ApiService
        nohup dotnet run &
        sleep 10
      env:
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: "http://localhost:5001"
        ConnectionStrings__privatesocial: "Server=localhost;Port=3306;Database=privatesocial;User=privatesocial_user;Password=privatesocial_password;"
        ConnectionStrings__redis: "localhost:6379"

    - name: Wait for API to be ready
      run: |
        echo "Waiting for API to be ready..."
        timeout 60 bash -c 'until curl -f http://localhost:5001/health; do sleep 2; done'

    - name: Run E2E tests
      working-directory: ./PrivateSocial.Web.React
      run: npm run test:e2e
      env:
        CI: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: PrivateSocial.Web.React/playwright-report/
        retention-days: 30

    - name: Upload test videos
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-videos
        path: PrivateSocial.Web.React/test-results/
        retention-days: 7