name: Frontend Validation

on:
  workflow_call:
  pull_request:
    paths:
      - 'PrivateSocial.Web.React/**'
      - '.github/workflows/frontend-validation.yml'

env:
  NODE_VERSION: '20.x'
  WORKING_DIR: './PrivateSocial.Web.React'

jobs:
  validate:
    name: Build and Test React
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.WORKING_DIR }}/package-lock.json

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ${{ env.WORKING_DIR }}/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint
      continue-on-error: false

    - name: Check TypeScript types
      run: npm run typecheck || npx tsc --noEmit
      continue-on-error: false

    - name: Build application
      run: npm run build

    - name: Run unit tests
      run: npm test -- --passWithNoTests || echo "No unit tests configured"
      env:
        CI: true

    - name: Check bundle size
      run: |
        echo "Build size analysis:"
        du -sh dist/ || true
        find dist -name "*.js" -exec du -h {} + | sort -rh | head -20 || true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: react-build
        path: ${{ env.WORKING_DIR }}/dist/
        retention-days: 7

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: frontend-test-results
        path: |
          ${{ env.WORKING_DIR }}/coverage/
          ${{ env.WORKING_DIR }}/test-results/
        retention-days: 7